/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JuWoj8013
 */
public class FormRockPaperScissors extends javax.swing.JFrame {
    int wins = 0;
    int loses = 0;
    int ties = 0;
    /**
     * Creates new form FormRockPaperScissors
     */
    public FormRockPaperScissors() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        HeadingLabel = new javax.swing.JLabel();
        RockLabel = new javax.swing.JLabel();
        PaperLabel = new javax.swing.JLabel();
        ScissorsLabel = new javax.swing.JLabel();
        UserChoiceLabel = new javax.swing.JLabel();
        UserChoiceText = new javax.swing.JTextField();
        GenerateBtn = new javax.swing.JButton();
        ComputerChoiceLabel = new javax.swing.JLabel();
        ComputerChoiceLabel2 = new javax.swing.JLabel();
        WinsLabel = new javax.swing.JLabel();
        LosesLabel = new javax.swing.JLabel();
        TiesLabel = new javax.swing.JLabel();
        WinsLabel2 = new javax.swing.JLabel();
        LosesLabel2 = new javax.swing.JLabel();
        TiesLabel2 = new javax.swing.JLabel();
        DisplayLabel = new javax.swing.JLabel();
        UserChoiceLabel3 = new javax.swing.JLabel();
        UserChoiceLabel4 = new javax.swing.JLabel();
        ResetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackgroundPanel.setBackground(new java.awt.Color(204, 204, 255));

        HeadingLabel.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        HeadingLabel.setText("Rock Paper Scissors");

        RockLabel.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 11)); // NOI18N
        RockLabel.setText("1.- Rock");

        PaperLabel.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 11)); // NOI18N
        PaperLabel.setText("2.- Paper");

        ScissorsLabel.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 11)); // NOI18N
        ScissorsLabel.setText("3.- Scissors");

        UserChoiceLabel.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 11)); // NOI18N
        UserChoiceLabel.setText("Enter your choice:");

        UserChoiceText.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 11)); // NOI18N

        GenerateBtn.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 11)); // NOI18N
        GenerateBtn.setText("Generate");
        GenerateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateBtnActionPerformed(evt);
            }
        });

        ComputerChoiceLabel.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 11)); // NOI18N
        ComputerChoiceLabel.setText("Computer choice:");

        ComputerChoiceLabel2.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 11)); // NOI18N

        WinsLabel.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 18)); // NOI18N
        WinsLabel.setText("Wins:");

        LosesLabel.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 18)); // NOI18N
        LosesLabel.setText("Loses:");

        TiesLabel.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 18)); // NOI18N
        TiesLabel.setText("Ties:");

        WinsLabel2.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 18)); // NOI18N

        LosesLabel2.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 18)); // NOI18N

        TiesLabel2.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 18)); // NOI18N

        DisplayLabel.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 36)); // NOI18N

        UserChoiceLabel3.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 11)); // NOI18N
        UserChoiceLabel3.setText("You chose:");

        UserChoiceLabel4.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 11)); // NOI18N

        ResetBtn.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 11)); // NOI18N
        ResetBtn.setText("Reset");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(WinsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LosesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LosesLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WinsLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addComponent(TiesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TiesLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(DisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addComponent(ResetBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(RockLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PaperLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ScissorsLabel))
                .addGap(33, 33, 33)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addComponent(HeadingLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserChoiceLabel)
                            .addComponent(ComputerChoiceLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComputerChoiceLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UserChoiceText, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GenerateBtn)
                        .addGap(45, 45, 45))
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addComponent(UserChoiceLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UserChoiceLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addComponent(HeadingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserChoiceLabel)
                    .addComponent(GenerateBtn)
                    .addComponent(UserChoiceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComputerChoiceLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PaperLabel)
                        .addComponent(ComputerChoiceLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserChoiceLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ScissorsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UserChoiceLabel3)))
                .addGap(28, 28, 28)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WinsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WinsLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LosesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LosesLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(DisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TiesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TiesLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ResetBtn)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * When user generates random computer response
     * @param evt 
     */
    private void GenerateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateBtnActionPerformed
    //Variables
    int userChoice;
    int computerNumber;
    
    //Changing Variables
    userChoice = Integer.parseInt(UserChoiceText.getText());
    computerNumber = (int)Math.round(Math.random()*3+1);
    //Computer Generated Display
        if (computerNumber == 1)
        {
            ComputerChoiceLabel2.setText("Rock");
        }
        if (computerNumber == 2)
        {
          ComputerChoiceLabel2.setText("Paper");          
        }
        if (computerNumber == 3)
        {
          ComputerChoiceLabel2.setText("Scissors");
        }
       
        //When User Chooses Rock 
        if (userChoice == 1)
        {
         UserChoiceLabel4.setText("Rock");
         if (computerNumber == 1)
         {
          DisplayLabel.setText("It's a tie!");
          ties = ties + 1;
         }
         if (computerNumber == 2)
         {
           DisplayLabel.setText("You lose!");
           loses = loses + 1;
         }
         if (computerNumber == 3)
         {
           DisplayLabel.setText("You win!");
           wins = wins + 1;
         }
        }
        //When User Chooses Paper
        if (userChoice == 2)
        {
          UserChoiceLabel4.setText("Paper");
          if (computerNumber == 1)
          {
            DisplayLabel.setText("You win!");
            wins = wins + 1;
          }
          if (computerNumber == 2)
          {
            DisplayLabel.setText("It's a tie!");
            ties = ties + 1;
          }
          if (computerNumber == 3)
          {
            DisplayLabel.setText("You lose!");
            loses = loses + 1;
          }
        }
        
        //When User Chooses Scissors
        if (userChoice == 3)
        {
          UserChoiceLabel4.setText("Scissors");
          if (computerNumber == 1)
          {
            DisplayLabel.setText("You lose!");
            loses = loses + 1;
          }
          if (computerNumber == 2)
          {
             DisplayLabel.setText("You win!");
             wins = wins + 1;
          }
          if (computerNumber == 3)
          {
             DisplayLabel.setText("It's a tie!");
             ties = ties + 1;
          }
        }
        
        //Setting Score
        WinsLabel2.setText("" + wins);
        LosesLabel2.setText("" + loses);
        TiesLabel2.setText("" + ties);
        
    }//GEN-LAST:event_GenerateBtnActionPerformed

    /**
     * When user resets score
     * @param evt 
     */
    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
       wins = 0;
       loses = 0;
       ties = 0;
       WinsLabel2.setText("" + wins);
       LosesLabel2.setText("" + loses);
       TiesLabel2.setText("" + ties);
    }//GEN-LAST:event_ResetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRockPaperScissors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRockPaperScissors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRockPaperScissors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRockPaperScissors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRockPaperScissors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel ComputerChoiceLabel;
    private javax.swing.JLabel ComputerChoiceLabel2;
    private javax.swing.JLabel DisplayLabel;
    private javax.swing.JButton GenerateBtn;
    private javax.swing.JLabel HeadingLabel;
    private javax.swing.JLabel LosesLabel;
    private javax.swing.JLabel LosesLabel2;
    private javax.swing.JLabel PaperLabel;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JLabel RockLabel;
    private javax.swing.JLabel ScissorsLabel;
    private javax.swing.JLabel TiesLabel;
    private javax.swing.JLabel TiesLabel2;
    private javax.swing.JLabel UserChoiceLabel;
    private javax.swing.JLabel UserChoiceLabel3;
    private javax.swing.JLabel UserChoiceLabel4;
    private javax.swing.JTextField UserChoiceText;
    private javax.swing.JLabel WinsLabel;
    private javax.swing.JLabel WinsLabel2;
    // End of variables declaration//GEN-END:variables
}
